import { ActionType } from 'redux-promise-middleware';

export const MENU_ADDED = "menuAdded";
export const MENU_UPDATED = "menuUpdated";
export const MENU_DELETED = "menuDeleted";
export const MENU_FETCHED = "menuFetched";
export const MENU_FILTERED = "menuFiltered";
export const MENU_CHECKED = "menuChecked";
export const MENU_CHANGE_QUANTITY = "menuQuantity";
export const MENU_FETCHED_PENDING = `${MENU_FETCHED}_${ActionType.Pending}`;
export const MENU_FETCHED_FULFILLED = `${MENU_FETCHED}_${ActionType.Fulfilled}`;
export const MENU_FETCHED_REJECTED = `${MENU_FETCHED}_${ActionType.Rejected}`;
export const MENU_FILTERED_PENDING = `${MENU_FILTERED}_${ActionType.Pending}`;
export const MENU_FILTERED_FULFILLED = `${MENU_FILTERED}_${ActionType.Fulfilled}`;
export const MENU_FILTERED_REJECTED = `${MENU_FILTERED}_${ActionType.Rejected}`;
export const LOGGED_IN = "loggedIn";
export const LOGGED_IN_PENDING = `${LOGGED_IN}_${ActionType.Pending}`;
export const LOGGED_IN_FULFILLED = `${LOGGED_IN}_${ActionType.Fulfilled}`;
export const LOGGED_IN_REJECTED = `${LOGGED_IN}_${ActionType.Rejected}`;
export const USER_REGISTERED = "userRegistered";
export const USER_REGISTERED_PENDING = `${USER_REGISTERED}_${ActionType.Pending}`;
export const USER_REGISTERED_FULFILLED = `${USER_REGISTERED}_${ActionType.Fulfilled}`;
export const USER_REGISTERED_REJECTED = `${USER_REGISTERED}_${ActionType.Rejected}`;
export const LOGGED_OUT = "loggedOut";